##############################################################################
# Template generated by SiliconSmart T-2022.03-SP2-1 (built on Jun 27, 2022 10:33:00) #
# SiliconSmart Path: /tools/Synopsys/siliconsmart/T-2022.03-SP2-1/linux64/bin/siliconsmart #
# Host Name: cad52, User Name: zhengyj, PID: 68719 #
# Directory: /data/zhengyj/OTFT_stdlib #
# Date Sat, 27 Dec 2025 13:20:17 CST #
#                                                                            #
# Copyright (C) 2022 Synopsys Inc.                                #
# This file contains confidential and proprietry information.                #
# All rights reserved.                                                       #
#                                                                            #
##############################################################################

set tempTestColl [ SBTestCollection automap ]


# Specifies the version of the template API expected by this file.
$tempTestColl setTemplateVer 7

## 
## Configuration Flags
$tempTestColl setConfigurationFlags { doTiming doPower }

## 
## Formal Ports
$tempTestColl makeFormalPorts {Q CK D QN}
$tempTestColl setParameter retention_ports {}
$tempTestColl setParameter synch_controls {}
$tempTestColl setParameter clock_ports {CK}
$tempTestColl setParameter asynch_ports {}
$tempTestColl setParameter asynch_ports_active_state {}

## 
## Tests

## 
## Test cmpw_hbm__CK__lh__CK__hl
set tempTest [ SBTest "cmpw_hbm__CK__lh__CK__hl" ]
$tempTest setTargets { cmpw_hbm__CK__lh__CK__hl }
$tempTest setTargetInputs {
  {CK lh}}

$tempTest setTargetOutputs {
  {Q lh}  {QN hl}}

$tempTest setTargetReferences {
  {CK hl}}

$tempTest setSwitchingInputs {
  {CK lh}}

$tempTest setSwitchingRefs {
  {CK hl}}

$tempTest setAnalysisType tranPlus

## 
## Sweep Specification
$tempTest setTagNumTableDimensions 1 mpw

## 
## Harnesses
$tempTest setAcquire 1

## 
## ACQ_1
set tempAcq [ SBMPWHBMAcquisition "ACQ_1" ]
$tempAcq setHarnessName default
$tempAcq setAcquire 1
$tempAcq setState "!D"
$tempAcq setStateCoverage "!D"
$tempAcq setWhen "!D"

## 
## Wavetable
set tempWT [ SBWaveTable ]
$tempWT setInterface { Q:out CK D QN:out } { initial_delay units ct default_slew stable cmpw min_cmpw max_cmpw opt_tolerance init_hbm degrade_cmpw }

$tempWT setStimulus                           {   CK   D    Q    QN    } {
                              "0"          {} {   0    0    1    0     }
                  "initial_delay" { in1 out } {   1    -    0    1     }
           "(initial_delay)+cmpw"     { in2 } {   0    -    -    -     }
"((initial_delay)+cmpw)+(stable)"          {} {   -    -    -    -     }
}

$tempWT addMeasurements {} {
  { tin_hbm_CK           Tin_hbm    { CK in1 } NO_USER SYS }
  { cmpw_hbm_CK          cmpw_hbm   { CK in1 CK in2 } NO_USER SYS }
  { tout_hbm_Q           Tout_hbm   { Q in1 0 1 } NO_USER SYS }
  { delay_hbm_CK_Q       delay_hbm  { CK in1 Q in1 0 } NO_USER SYS }
  { fallback_hbm_Q       fallback_hbm { Q in1 0 } NO_USER SYS }
  { tout_hbm_QN          Tout_hbm   { QN in1 0 1 } NO_USER SYS }
  { delay_hbm_CK_QN      delay_hbm  { CK in1 QN in1 0 } NO_USER SYS }
  { fallback_hbm_QN      fallback_hbm { QN in1 0 } NO_USER SYS }
  { sis_pass_fail        passfail_hbm { 0 CK CK } NO_USER SYS }
}

$tempWT addHbm    cmpw    min_cmpw    max_cmpw    delay_hbm_CK_Q    independent   { Q relative-degradation QN relative-degradation }   { Q positive-side QN positive-side }   { Q 0.2 -1 QN 0.2 -1 }   { Q 1e-11 1e-08 -1 QN 1e-11 1e-08 -1 }  { (fallback_hbm__Q__hl_trig-tout_hbm__Q__hl_targ) (fallback_hbm__Q__hl_targ-tout_hbm__Q__hl_trig) (fallback_hbm__QN__lh_trig-tout_hbm__QN__lh_targ) (fallback_hbm__QN__lh_targ-tout_hbm__QN__lh_trig) }   {  }  { Q hl QN lh }  {  }  { cmpw_hbm__CK__lh__CK__hl_trig cmpw_hbm__CK__lh__CK__hl_targ tin_hbm__CK__lh_trig tin_hbm__CK__lh_targ tout_hbm__Q__hl_trig tout_hbm__Q__hl_targ delay_hbm__CK__lh__Q__hl_trig delay_hbm__CK__lh__Q__hl_targ tout_hbm__QN__lh_trig tout_hbm__QN__lh_targ delay_hbm__CK__lh__QN__lh_trig delay_hbm__CK__lh__QN__lh_targ } {  } { relative Q delay_hbm__CK__lh__Q__hl_value relative QN delay_hbm__CK__lh__QN__lh_value } { cmpw_hbm__CK__lh__CK__hl_value } {  } {  } expand None opt_tolerance None None max_cmpw "1"
$tempWT bindInterface { Q CK D QN } { 10e-12 CK[cycle_time] CK[cycle_time] CK[default_slew] max(CK[stable_time],Q[stable_time],QN[stable_time]) CK[max_cmpw] CK[min_cmpw] CK[max_cmpw] CK[constraint_resolution] CK[min_cmpw] 0.0 }
$tempAcq addWaveTable $tempWT
release_obj $tempWT

## 
## Initialization Acquisition
$tempAcq setInitializationAcquisition initialization__ACQ_1

## 
## Sweep Specification
$tempAcq setTagNumTableDimensions 1 mpw

## 
## Harnesses

set tempHarness [ SBHarness default ]
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement capacitor
$tempTopOp setElementName cap_Q
$tempTopOp setOperation insert
$tempTopOp setNodes {Q Q[logic_low_name]}
$tempTopOp setParam {load_Q}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement capacitor
$tempTopOp setElementName cap_QN
$tempTopOp setOperation insert
$tempTopOp setNodes {QN QN[logic_low_name]}
$tempTopOp setParam {load_QN}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
$tempAcq addHarness $tempHarness
release_obj $tempHarness

$tempAcq setHarnessName default
$tempTest addAcquisition $tempAcq
release_obj $tempAcq

$tempTestColl addTest $tempTest
release_obj $tempTest

set tempTestColl

