##############################################################################
# Template generated by SiliconSmart T-2022.03-SP2-1 (built on Jun 27, 2022 10:33:00) #
# SiliconSmart Path: /tools/Synopsys/siliconsmart/T-2022.03-SP2-1/linux64/bin/siliconsmart #
# Host Name: cad52, User Name: zhengyj, PID: 68719 #
# Directory: /data/zhengyj/OTFT_stdlib #
# Date Sat, 27 Dec 2025 13:20:17 CST #
#                                                                            #
# Copyright (C) 2022 Synopsys Inc.                                #
# This file contains confidential and proprietry information.                #
# All rights reserved.                                                       #
#                                                                            #
##############################################################################

set tempTestColl [ SBTestCollection automap ]


# Specifies the version of the template API expected by this file.
$tempTestColl setTemplateVer 7

## 
## Configuration Flags
$tempTestColl setConfigurationFlags { doTiming doPower }

## 
## Formal Ports
$tempTestColl makeFormalPorts {Q CK D QN}
$tempTestColl setParameter retention_ports {}
$tempTestColl setParameter synch_controls {}
$tempTestColl setParameter clock_ports {CK}
$tempTestColl setParameter asynch_ports {}
$tempTestColl setParameter asynch_ports_active_state {}

## 
## Tests

## 
## Test setup_hbm__D__lh__CK__lh
set tempTest [ SBTest "setup_hbm__D__lh__CK__lh" ]
$tempTest setTargets { setup_hbm__D__lh__CK__lh }
$tempTest setTargetInputs {
  {D lh}}

$tempTest setTargetOutputs {
  {Q lh}  {QN hl}}

$tempTest setTargetReferences {
  {CK lh}}

$tempTest setSwitchingInputs {
  {D lh}}

$tempTest setSwitchingRefs {
  {CK lh}}

$tempTest setAnalysisType tranPlus

## 
## Sweep Specification
$tempTest setTagNumTableDimensions 0 mpw

## 
## Harnesses
$tempTest setAcquire 1

## 
## ACQ_1
set tempAcq [ SBConstraintHBMAcquisition "ACQ_1" ]
$tempAcq setHarnessName default
$tempAcq setAcquire 1
$tempAcq setState "1"
$tempAcq setStateCoverage "1"
$tempAcq setWhen "1"

## 
## Wavetable
set tempWT [ SBWaveTable ]
$tempWT setInterface { Q:out CK D QN:out } { initial_delay units ct default_slew stable driver_delay_D driver_delay_CK setup min_setup max_setup opt_tolerance init_hbm degrade_setup }

$tempWT setStimulus                            {   CK   D    Q    QN    } {
                               "0"          {} {   0    0    0    1     }
                   "initial_delay"     { in1 } {   -    1    -    -     }
           "(initial_delay)+setup" { in2 out } {   1    -    1    0     }
"((initial_delay)+setup)+(stable)"          {} {   -    -    -    -     }
}

$tempWT addMeasurements {} {
  { tin_D                Tin        { D in1 } NO_USER SYS }
  { tin_CK               Tin        { CK in2 } NO_USER SYS }
  { setup_hbm_D_CK       setup_hbm  { D in1 CK in2 0 } NO_USER SYS }
  { tout_hbm_Q           Tout_hbm   { Q in2 0 1 } NO_USER SYS }
  { delay_hbm_CK_Q       delay_hbm  { CK in2 Q in2 0 } NO_USER SYS }
  { fallback_hbm_Q       fallback_hbm { Q in2 0 } NO_USER SYS }
  { tout_hbm_QN          Tout_hbm   { QN in2 0 1 } NO_USER SYS }
  { delay_hbm_CK_QN      delay_hbm  { CK in2 QN in2 0 } NO_USER SYS }
  { fallback_hbm_QN      fallback_hbm { QN in2 0 } NO_USER SYS }
  { sis_pass_fail        passfail_hbm { 0 D CK } NO_USER SYS }
}

$tempWT addHbm    setup    min_setup    max_setup    delay_hbm_CK_Q    independent   { Q relative-degradation QN relative-degradation }   { Q positive-side QN positive-side }   { Q 0.2 -1 QN 0.2 -1 }   { Q 1e-11 1e-08 -1 QN 1e-11 1e-08 -1 }  { (fallback_hbm__Q__lh_trig-tout_hbm__Q__lh_targ) (fallback_hbm__Q__lh_targ-tout_hbm__Q__lh_trig) (fallback_hbm__QN__hl_trig-tout_hbm__QN__hl_targ) (fallback_hbm__QN__hl_targ-tout_hbm__QN__hl_trig) }   {  }  { Q lh QN hl }  {  }  { setup_hbm__D__lh__CK__lh_trig setup_hbm__D__lh__CK__lh_targ tin__D__lh_trig tin__D__lh_targ tin__CK__lh_trig tin__CK__lh_targ tout_hbm__Q__lh_trig tout_hbm__Q__lh_targ delay_hbm__CK__lh__Q__lh_trig delay_hbm__CK__lh__Q__lh_targ tout_hbm__QN__hl_trig tout_hbm__QN__hl_targ delay_hbm__CK__lh__QN__hl_trig delay_hbm__CK__lh__QN__hl_targ } {  } { relative Q delay_hbm__CK__lh__Q__lh_value relative QN delay_hbm__CK__lh__QN__hl_value } { setup_hbm__D__lh__CK__lh_value } {  } {  } pass None opt_tolerance (driver_delay_D-driver_delay_CK)+(1.99*opt_tolerance)+(0.15*(slew_D+slew_CK)) driver_delay_D-driver_delay_CK min_setup "1"
$tempWT bindInterface { Q CK D QN } { 10e-12 D[cycle_time] D[cycle_time] D[default_slew] max(D[stable_time],Q[stable_time],QN[stable_time]) (slew_D*0.5)/(0.7-0.3) (slew_CK*0.5)/(0.7-0.3) D[max_setup] D[min_setup] D[max_setup] D[constraint_resolution] driver_delay_D-driver_delay_CK 0.0 }
$tempAcq addWaveTable $tempWT
release_obj $tempWT

## 
## Initialization Acquisition
$tempAcq setInitializationAcquisition initialization__ACQ_4

## 
## Sweep Specification
$tempAcq setTagNumTableDimensions 0 mpw

## 
## Harnesses

set tempHarness [ SBHarness default ]
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement capacitor
$tempTopOp setElementName cap_Q
$tempTopOp setOperation insert
$tempTopOp setNodes {Q Q[logic_low_name]}
$tempTopOp setParam {load_Q}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement capacitor
$tempTopOp setElementName cap_QN
$tempTopOp setOperation insert
$tempTopOp setNodes {QN QN[logic_low_name]}
$tempTopOp setParam {load_QN}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
$tempAcq addHarness $tempHarness
release_obj $tempHarness

$tempAcq setHarnessName default
$tempTest addAcquisition $tempAcq
release_obj $tempAcq

$tempTestColl addTest $tempTest
release_obj $tempTest

set tempTestColl

