##############################################################################
# Template generated by SiliconSmart T-2022.03-SP2-1 (built on Jun 27, 2022 10:33:00) #
# SiliconSmart Path: /tools/Synopsys/siliconsmart/T-2022.03-SP2-1/linux64/bin/siliconsmart #
# Host Name: cad52, User Name: zhengyj, PID: 122380 #
# Directory: /data/zhengyj/OTFT_stdlib #
# Date Thu, 25 Dec 2025 13:08:51 CST #
#                                                                            #
# Copyright (C) 2022 Synopsys Inc.                                #
# This file contains confidential and proprietry information.                #
# All rights reserved.                                                       #
#                                                                            #
##############################################################################

set tempTestColl [ SBTestCollection automap ]


# Specifies the version of the template API expected by this file.
$tempTestColl setTemplateVer 7

## 
## Configuration Flags
$tempTestColl setConfigurationFlags { doTiming doPower }

## 
## Formal Ports
$tempTestColl makeFormalPorts {Q CK D QN}
$tempTestColl setParameter retention_ports {}
$tempTestColl setParameter synch_controls {}
$tempTestColl setParameter clock_ports {CK}
$tempTestColl setParameter asynch_ports {}
$tempTestColl setParameter asynch_ports_active_state {}

## 
## Tests

## 
## Test delay__CK__lh__Q__hl
set tempTest [ SBTest "delay__CK__lh__Q__hl" ]
$tempTest setTargets { delay__CK__lh__Q__hl Cin__CK__lh Tout__Q__hl cap_energy__QN__lh cap_energy__Q__hl energy1__CK__lh__Q__hl__VDD energy1__CK__lh__Q__hl__VSS energy__CK__lh__Q__hl leakage_power1__VDD leakage_power1__VSS leakage_power2__VDD leakage_power2__VSS }
$tempTest setTargetInputs {
  {CK lh}}

$tempTest setTargetOutputs {
  {Q hl}  {QN lh}}

$tempTest setSwitchingInputs {
  {CK lh}}

$tempTest setAnalysisType tranPlus

## 
## Sweep Specification
$tempTest setTagNumTableDimensions 0 mpw

## 
## Harnesses
$tempTest setAcquire 1

## 
## ACQ_1
set tempAcq [ SBDelayAcquisition "ACQ_1" ]
$tempAcq setHarnessName default
$tempAcq setAcquire 1
$tempAcq setState "!D"
$tempAcq setStateCoverage "!D"
$tempAcq setAdditionalStateCoverage "!D" "leakage_power2__VSS"
$tempAcq setAdditionalStateCoverage "!D" "energy1__CK__lh__Q__hl__VSS"
$tempAcq setAdditionalStateCoverage "!D" "energy1__CK__lh__Q__hl__VDD"
$tempAcq setAdditionalStateCoverage "!D" "cap_energy__Q__hl"
$tempAcq setAdditionalStateCoverage "!D" "leakage_power1__VSS"
$tempAcq setAdditionalStateCoverage "!D" "leakage_power1__VDD"
$tempAcq setAdditionalStateCoverage "!D" "energy__CK__lh__Q__hl"
$tempAcq setAdditionalStateCoverage "!D" "cap_energy__QN__lh"
$tempAcq setAdditionalStateCoverage "!D" "leakage_power2__VDD"
$tempAcq setWhen "1"
$tempAcq setDoEcsmSi 0
$tempAcq setAdditionalWhen "1" "leakage_power2__VSS"
$tempAcq setAdditionalWhen "1" "energy1__CK__lh__Q__hl__VSS"
$tempAcq setAdditionalWhen "1" "energy1__CK__lh__Q__hl__VDD"
$tempAcq setAdditionalWhen "1" "cap_energy__Q__hl"
$tempAcq setAdditionalWhen "1" "leakage_power1__VSS"
$tempAcq setAdditionalWhen "1" "leakage_power1__VDD"
$tempAcq setAdditionalWhen "1" "energy__CK__lh__Q__hl"
$tempAcq setAdditionalWhen "1" "cap_energy__QN__lh"
$tempAcq setAdditionalWhen "1" "leakage_power2__VDD"

## 
## Wavetable
set tempWT [ SBWaveTable ]
$tempWT setInterface { Q:inout CK D QN:out } { initial_delay units ct default_slew pp energy_change_threshold energy_change_abs_threshold }

$tempWT setStimulus                  {   CK   D    Q    QN    } {
                   "0"            {} {   0    0    Z,1  0     }
       "initial_delay" { start out } {   1    -    Z,0  1     }
"(initial_delay)+(pp)"            {} {   -    -    -,-  -     }
}

$tempWT addMeasurements {} {
  { tin_CK               Tin        { CK start } NO_USER SYS }
  { cin_CK               Cin        { CK start } NO_USER SYS }
  { tout_Q               Tout       { Q out } NO_USER SYS }
  { tout_QN              Tout       { QN out } NO_USER SYS }
  { delay_CK_Q           delay      { CK start Q out } NO_USER SYS }
  { energy__CK__lh__Q__hl energy     { start pp energy_change_threshold energy_change_abs_threshold 0 } NO_USER SYS }
  { cell_power_period    export_expr { pp } }
  { energy1__CK__lh__Q__hl__VDD energy1    { start pp energy_change_threshold energy_change_abs_threshold 0 VDD } }
  { leakage_power1__VDD  leakage_power1 { initial_delay+0.95*pp initial_delay+pp VDD } }
  { leakage_power2__VDD  leakage_power2 { initial_delay+0.90*pp initial_delay+0.95*pp VDD } }
  { energy1__CK__lh__Q__hl__VSS energy1    { start pp energy_change_threshold energy_change_abs_threshold 0 VSS } }
  { leakage_power1__VSS  leakage_power1 { initial_delay+0.95*pp initial_delay+pp VSS } }
  { leakage_power2__VSS  leakage_power2 { initial_delay+0.90*pp initial_delay+0.95*pp VSS } }
  { cap_energy__Q__hl    cap_energy { start pp cap_Q Q 0 } }
  { cap_energy__QN__lh   cap_energy { start pp cap_QN QN 0 } }
}

$tempWT bindInterface { Q CK D QN } { 10e-12 CK[cycle_time] CK[cycle_time] CK[default_slew] cell_power_period power_stabilization_threshold power_stabilization_threshold_absolute }
$tempAcq addWaveTable $tempWT
release_obj $tempWT

## 
## Initialization Acquisition
$tempAcq setInitializationAcquisition initialization__ACQ_1

## 
## Sweep Specification
$tempAcq setTagNumTableDimensions 0 mpw

## 
## Harnesses

set tempHarness [ SBHarness default ]
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement dcvs
$tempTopOp setElementName cap_ground_Q
$tempTopOp setOperation insert
$tempTopOp setNodes {ground_Q 0}
$tempTopOp setParam {0}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement capacitor
$tempTopOp setElementName cap_Q
$tempTopOp setOperation insert
$tempTopOp setNodes {Q ground_Q}
$tempTopOp setParam {load_Q}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement dcvs
$tempTopOp setElementName cap_ground_QN
$tempTopOp setOperation insert
$tempTopOp setNodes {ground_QN 0}
$tempTopOp setParam {0}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement capacitor
$tempTopOp setElementName cap_QN
$tempTopOp setOperation insert
$tempTopOp setNodes {QN ground_QN}
$tempTopOp setParam {load_QN}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
$tempAcq addHarness $tempHarness
release_obj $tempHarness

$tempAcq setHarnessName default
$tempTest addAcquisition $tempAcq
release_obj $tempAcq

$tempTestColl addTest $tempTest
release_obj $tempTest

set tempTestColl

