##############################################################################
# Template generated by SiliconSmart T-2022.03-SP2-1 (built on Jun 27, 2022 10:33:00) #
# SiliconSmart Path: /tools/Synopsys/siliconsmart/T-2022.03-SP2-1/linux64/bin/siliconsmart #
# Host Name: cad52, User Name: zhengyj, PID: 68719 #
# Directory: /data/zhengyj/OTFT_stdlib #
# Date Sat, 27 Dec 2025 13:20:19 CST #
#                                                                            #
# Copyright (C) 2022 Synopsys Inc.                                #
# This file contains confidential and proprietry information.                #
# All rights reserved.                                                       #
#                                                                            #
##############################################################################

set tempTestColl [ SBTestCollection automap ]


# Specifies the version of the template API expected by this file.
$tempTestColl setTemplateVer 7

## 
## Configuration Flags
$tempTestColl setConfigurationFlags { doTiming doPower }

## 
## Formal Ports
$tempTestColl makeFormalPorts {IN1 IN2 OUT}
$tempTestColl setParameter retention_ports {}
$tempTestColl setParameter synch_controls {}
$tempTestColl setParameter clock_ports {}
$tempTestColl setParameter asynch_ports {}
$tempTestColl setParameter asynch_ports_active_state {}

## 
## Tests

## 
## Test delay__IN1__hl__OUT__lh
set tempTest [ SBTest "delay__IN1__hl__OUT__lh" ]
$tempTest setTargets { delay__IN1__hl__OUT__lh Cin__IN1__hl Tout__OUT__lh cap_energy__OUT__lh energy1__IN1__hl__OUT__lh__VDD energy1__IN1__hl__OUT__lh__VSS energy__IN1__hl__OUT__lh leakage_power1__VDD leakage_power1__VSS leakage_power2__VDD leakage_power2__VSS }
$tempTest setTargetInputs {
  {IN1 hl}}

$tempTest setTargetOutputs {
  {OUT lh}}

$tempTest setSwitchingInputs {
  {IN1 hl}}

$tempTest setAnalysisType tranPlus

## 
## Sweep Specification
$tempTest setTagNumTableDimensions 0 mpw

## 
## Harnesses
$tempTest setAcquire 1

## 
## ACQ_1
set tempAcq [ SBDelayAcquisition "ACQ_1" ]
$tempAcq setHarnessName default
$tempAcq setAcquire 1
$tempAcq setState "!IN2"
$tempAcq setStateCoverage "!IN2"
$tempAcq setAdditionalStateCoverage "!IN2" "cap_energy__OUT__lh"
$tempAcq setAdditionalStateCoverage "!IN2" "energy1__IN1__hl__OUT__lh__VDD"
$tempAcq setAdditionalStateCoverage "!IN2" "leakage_power2__VSS"
$tempAcq setAdditionalStateCoverage "!IN2" "energy1__IN1__hl__OUT__lh__VSS"
$tempAcq setAdditionalStateCoverage "!IN2" "leakage_power1__VSS"
$tempAcq setAdditionalStateCoverage "!IN2" "leakage_power1__VDD"
$tempAcq setAdditionalStateCoverage "!IN2" "leakage_power2__VDD"
$tempAcq setAdditionalStateCoverage "!IN2" "energy__IN1__hl__OUT__lh"
$tempAcq setWhen "1"
$tempAcq setDoEcsmSi 0
$tempAcq setAdditionalWhen "1" "cap_energy__OUT__lh"
$tempAcq setAdditionalWhen "1" "energy1__IN1__hl__OUT__lh__VDD"
$tempAcq setAdditionalWhen "1" "leakage_power2__VSS"
$tempAcq setAdditionalWhen "1" "energy1__IN1__hl__OUT__lh__VSS"
$tempAcq setAdditionalWhen "1" "leakage_power1__VSS"
$tempAcq setAdditionalWhen "1" "leakage_power1__VDD"
$tempAcq setAdditionalWhen "1" "leakage_power2__VDD"
$tempAcq setAdditionalWhen "1" "energy__IN1__hl__OUT__lh"

## 
## Wavetable
set tempWT [ SBWaveTable ]
$tempWT setInterface { IN1 IN2 OUT:inout } { initial_delay units ct default_slew pp energy_change_threshold energy_change_abs_threshold }

$tempWT setStimulus                  {   IN1  IN2  OUT   } {
                   "0"            {} {   1    0    Z,0   }
       "initial_delay" { start out } {   0    -    Z,1   }
"(initial_delay)+(pp)"            {} {   -    -    -,-   }
}

$tempWT addMeasurements {} {
  { tin_IN1              Tin        { IN1 start } NO_USER SYS }
  { cin_IN1              Cin        { IN1 start } NO_USER SYS }
  { tout_OUT             Tout       { OUT out } NO_USER SYS }
  { delay_IN1_OUT        delay      { IN1 start OUT out } NO_USER SYS }
  { energy__IN1__hl__OUT__lh energy     { start pp energy_change_threshold energy_change_abs_threshold 0 } NO_USER SYS }
  { cell_power_period    export_expr { pp } }
  { energy1__IN1__hl__OUT__lh__VDD energy1    { start pp energy_change_threshold energy_change_abs_threshold 0 VDD } }
  { leakage_power1__VDD  leakage_power1 { initial_delay+0.95*pp initial_delay+pp VDD } }
  { leakage_power2__VDD  leakage_power2 { initial_delay+0.90*pp initial_delay+0.95*pp VDD } }
  { energy1__IN1__hl__OUT__lh__VSS energy1    { start pp energy_change_threshold energy_change_abs_threshold 0 VSS } }
  { leakage_power1__VSS  leakage_power1 { initial_delay+0.95*pp initial_delay+pp VSS } }
  { leakage_power2__VSS  leakage_power2 { initial_delay+0.90*pp initial_delay+0.95*pp VSS } }
  { cap_energy__OUT__lh  cap_energy { start pp cap_OUT OUT 0 } }
}

$tempWT bindInterface { IN1 IN2 OUT } { 10e-12 IN1[cycle_time] IN1[cycle_time] IN1[default_slew] cell_power_period power_stabilization_threshold power_stabilization_threshold_absolute }
$tempAcq addWaveTable $tempWT
release_obj $tempWT

## 
## Sweep Specification
$tempAcq setTagNumTableDimensions 0 mpw

## 
## Harnesses

set tempHarness [ SBHarness default ]
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement dcvs
$tempTopOp setElementName cap_ground_OUT
$tempTopOp setOperation insert
$tempTopOp setNodes {ground_OUT 0}
$tempTopOp setParam {0}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement capacitor
$tempTopOp setElementName cap_OUT
$tempTopOp setOperation insert
$tempTopOp setNodes {OUT ground_OUT}
$tempTopOp setParam {load_OUT}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
$tempAcq addHarness $tempHarness
release_obj $tempHarness

$tempAcq setHarnessName default
$tempTest addAcquisition $tempAcq
release_obj $tempAcq

$tempTestColl addTest $tempTest
release_obj $tempTest

set tempTestColl

