/*
###############################################################
#  Generated by:      Cadence Innovus 19.13-s080_1
#  OS:                Linux x86_64(Host ID cad52)
#  Generated on:      Sat Dec 27 21:06:22 2025
#  Design:            half_adder
#  Command:           saveNetlist -includePowerGround -excludeLeafCell /data/zhengyj/OTFT_stdlib/OTFT_stdlib_innovus/half_adder/output/half_adder.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Ultra(TM) in wire load mode
// Version   : T-2022.03-SP2
// Date      : Sat Dec 27 16:11:21 2025
/////////////////////////////////////////////////////////////
module half_adder (
	CLK, 
	reset, 
	in1, 
	in2, 
	sum, 
	cout, 
	VDD, 
	VSS);
   input CLK;
   input reset;
   input in1;
   input in2;
   output sum;
   output cout;
   inout VDD;
   inout VSS;

   // Internal wires
   wire N5;
   wire N6;
   wire n50;
   wire n60;
   wire n7;
   wire n8;

   // Module instantiations
   DFFD1 sum_reg (
	.CK(CLK),
	.D(N5),
	.Q(sum),
	.QN(), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFD1 cout_reg (
	.CK(CLK),
	.D(N6),
	.Q(cout),
	.QN(), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2D1 U9 (
	.IN1(in2),
	.IN2(in1),
	.OUT(n50), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2D1 U10 (
	.IN1(reset),
	.IN2(n50),
	.OUT(N6), 
	.VSS(VSS), 
	.VDD(VDD));
   INVD1 U11 (
	.IN(reset),
	.OUT(n60), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2D1 U12 (
	.IN1(n60),
	.IN2(n50),
	.OUT(n8), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2D1 U13 (
	.IN1(in2),
	.IN2(in1),
	.OUT(n7), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2D1 U14 (
	.IN1(n8),
	.IN2(n7),
	.OUT(N5), 
	.VSS(VSS), 
	.VDD(VDD));
endmodule

