###############################################################
#  Generated by:      Cadence Innovus 19.13-s080_1
#  OS:                Linux x86_64(Host ID cad52)
#  Generated on:      Mon Jan  5 21:18:24 2026
#  Design:            half_adder
#  Command:           create_ccopt_clock_tree_spec -file cts.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# Clocks present at pin CLK
#   CLK (period 20000000.000ns) in timing_config function([./netlist/half_adder.sdc])
create_ccopt_clock_tree -name CLK -source CLK -no_skew_group

set_ccopt_property source_driver -clock_tree CLK {INVD1/IN INVD1/OUT}
# Clock period setting for source pin of CLK
set_ccopt_property clock_period -pin CLK 2e+07

# Skew group to balance non generated clock:CLK in timing_config:function (sdc ./netlist/half_adder.sdc)
create_ccopt_skew_group -name CLK/function -sources CLK -auto_sinks
set_ccopt_property include_source_latency -skew_group CLK/function true
set_ccopt_property extracted_from_clock_name -skew_group CLK/function CLK
set_ccopt_property extracted_from_constraint_mode_name -skew_group CLK/function function
set_ccopt_property extracted_from_delay_corners -skew_group CLK/function {typical typical}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

