##############################################################################
# Template generated by SiliconSmart T-2022.03-SP2-1 (built on Jun 27, 2022 10:33:00) #
# SiliconSmart Path: /tools/Synopsys/siliconsmart/T-2022.03-SP2-1/linux64/bin/siliconsmart #
# Host Name: cad52, User Name: zhengyj, PID: 77857 #
# Directory: /data/zhengyj/OTFT_stdlib #
# Date Thu, 25 Dec 2025 16:16:03 CST #
#                                                                            #
# Copyright (C) 2022 Synopsys Inc.                                #
# This file contains confidential and proprietry information.                #
# All rights reserved.                                                       #
#                                                                            #
##############################################################################

set tempTestColl [ SBTestCollection automap ]


# Specifies the version of the template API expected by this file.
$tempTestColl setTemplateVer 7

## 
## Configuration Flags
$tempTestColl setConfigurationFlags { doTiming doPower }

## 
## Formal Ports
$tempTestColl makeFormalPorts {Q CK D QN}
$tempTestColl setParameter retention_ports {}
$tempTestColl setParameter synch_controls {}
$tempTestColl setParameter clock_ports {CK}
$tempTestColl setParameter asynch_ports {}
$tempTestColl setParameter asynch_ports_active_state {}

## 
## Tests

## 
## Test energy__CK__hl
set tempTest [ SBTest "energy__CK__hl" ]
$tempTest setTargets { energy__CK__hl Cin__CK__hl energy1__CK__hl__VDD energy1__CK__hl__VSS leakage_power1__VDD leakage_power1__VSS leakage_power2__VDD leakage_power2__VSS }
$tempTest setTargetInputs {
  {CK hl}}

$tempTest setSwitchingInputs {
  {CK hl}}

$tempTest setAnalysisType tranPlus

## 
## Sweep Specification
$tempTest setTagNumTableDimensions 0 mpw

## 
## Harnesses
$tempTest setAcquire 1

## 
## ACQ_1
set tempAcq [ SBEnergyAcquisition "ACQ_1" ]
$tempAcq setHarnessName default
$tempAcq setAcquire 1
$tempAcq setState "!D&!Q&QN"
$tempAcq setStateCoverage "1"
$tempAcq setAdditionalStateCoverage "1" "Cin__CK__hl"
$tempAcq setWhen "1"
$tempAcq setAdditionalWhen "1" "Cin__CK__hl"

## 
## Wavetable
set tempWT [ SBWaveTable ]
$tempWT setInterface { Q:out CK D QN:out } { initial_delay units ct default_slew pp energy_change_threshold energy_change_abs_threshold }

$tempWT setStimulus              {   CK   D    Q    QN    } {
                   "0"        {} {   1    0    0    1     }
       "initial_delay" { start } {   0    -    -    -     }
"(initial_delay)+(pp)"        {} {   -    -    -    -     }
}

$tempWT addMeasurements {} {
  { tin_CK               Tin        { CK start } NO_USER SYS }
  { cin_CK               Cin        { CK start } NO_USER SYS }
  { energy__CK__hl       energy     { start pp energy_change_threshold energy_change_abs_threshold 0 } NO_USER SYS }
  { cell_power_period    export_expr { pp } }
  { energy1__CK__hl__VDD energy1    { start pp energy_change_threshold energy_change_abs_threshold 0 VDD } }
  { leakage_power1__VDD  leakage_power1 { initial_delay+0.95*pp initial_delay+pp VDD } }
  { leakage_power2__VDD  leakage_power2 { initial_delay+0.90*pp initial_delay+0.95*pp VDD } }
  { energy1__CK__hl__VSS energy1    { start pp energy_change_threshold energy_change_abs_threshold 0 VSS } }
  { leakage_power1__VSS  leakage_power1 { initial_delay+0.95*pp initial_delay+pp VSS } }
  { leakage_power2__VSS  leakage_power2 { initial_delay+0.90*pp initial_delay+0.95*pp VSS } }
}

$tempWT bindInterface { Q CK D QN } { 10e-12 CK[cycle_time] CK[cycle_time] CK[default_slew] cell_power_period power_stabilization_threshold power_stabilization_threshold_absolute }
$tempAcq addWaveTable $tempWT
release_obj $tempWT

## 
## Initialization Acquisition
$tempAcq setInitializationAcquisition initialization__ACQ_3

## 
## Sweep Specification
$tempAcq setTagNumTableDimensions 0 mpw

## 
## Harnesses

set tempHarness [ SBHarness default ]
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement dcvs
$tempTopOp setElementName cap_ground_Q
$tempTopOp setOperation insert
$tempTopOp setNodes {ground_Q 0}
$tempTopOp setParam {0}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement capacitor
$tempTopOp setElementName cap_Q
$tempTopOp setOperation insert
$tempTopOp setNodes {Q ground_Q}
$tempTopOp setParam {load_Q}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement dcvs
$tempTopOp setElementName cap_ground_QN
$tempTopOp setOperation insert
$tempTopOp setNodes {ground_QN 0}
$tempTopOp setParam {0}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement capacitor
$tempTopOp setElementName cap_QN
$tempTopOp setOperation insert
$tempTopOp setNodes {QN ground_QN}
$tempTopOp setParam {load_QN}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
$tempAcq addHarness $tempHarness
release_obj $tempHarness

$tempAcq setHarnessName default
$tempTest addAcquisition $tempAcq
release_obj $tempAcq

$tempTestColl addTest $tempTest
release_obj $tempTest

set tempTestColl

