##############################################################################
# Template generated by SiliconSmart T-2022.03-SP2-1 (built on Jun 27, 2022 10:33:00) #
# SiliconSmart Path: /tools/Synopsys/siliconsmart/T-2022.03-SP2-1/linux64/bin/siliconsmart #
# Host Name: cad52, User Name: zhengyj, PID: 77857 #
# Directory: /data/zhengyj/OTFT_stdlib #
# Date Thu, 25 Dec 2025 16:16:03 CST #
#                                                                            #
# Copyright (C) 2022 Synopsys Inc.                                #
# This file contains confidential and proprietry information.                #
# All rights reserved.                                                       #
#                                                                            #
##############################################################################

set tempTestColl [ SBTestCollection automap ]


# Specifies the version of the template API expected by this file.
$tempTestColl setTemplateVer 7

## 
## Configuration Flags
$tempTestColl setConfigurationFlags { doTiming doPower }

## 
## Formal Ports
$tempTestColl makeFormalPorts {Q CK D QN}
$tempTestColl setParameter retention_ports {}
$tempTestColl setParameter synch_controls {}
$tempTestColl setParameter clock_ports {CK}
$tempTestColl setParameter asynch_ports {}
$tempTestColl setParameter asynch_ports_active_state {}

## 
## Tests

## 
## Test initialization
set tempTest [ SBTest "initialization" ]
$tempTest setTargets { initialization }
$tempTest setTargetOutputs {
  {Q lh}  {QN hl}}

$tempTest setSwitchingInputs {
  {CK lh}}

$tempTest setSwitchingRefs {
  {CK hl}}

$tempTest setAnalysisType tranPlus

## 
## Sweep Specification

## 
## Harnesses
$tempTest setAcquire 1

## 
## ACQ_6
set tempAcq [ SBInitializationAcquisition "ACQ_6" ]
$tempAcq setHarnessName default
$tempAcq setAcquire 1
$tempAcq setState "1"
$tempAcq setStateCoverage "1"

## 
## Wavetable
set tempWT [ SBWaveTable ]
$tempWT setInterface { Q:out CK D QN:out } { initial_delay ct units default_slew }

$tempWT setStimulus                         {   CK   D    Q    QN    } {
                                "0"      {} {   0    1    1    0     }
                    "initial_delay"      {} {   1    -    1    0     }
          "initial_delay+0.5*units" { in1 } {   -    0    -    -     }
"(initial_delay+0.5*units)+(units)"      {} {   -    -    -    -     }
}

$tempWT addMeasurements {} {
  { initialization       initialization { DFFD1 macro } NO_USER SYS }
}

$tempWT bindInterface { Q CK D QN } { cell_initial_delay cell_cycle_time cell_cycle_time Q[default_slew] }
$tempAcq addWaveTable $tempWT
release_obj $tempWT

## 
## Sweep Specification

## 
## Harnesses

set tempHarness [ SBHarness default ]
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement capacitor
$tempTopOp setElementName cap_Q
$tempTopOp setOperation insert
$tempTopOp setNodes {Q Q[logic_low_name]}
$tempTopOp setParam {load_Q}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement capacitor
$tempTopOp setElementName cap_QN
$tempTopOp setOperation insert
$tempTopOp setNodes {QN QN[logic_low_name]}
$tempTopOp setParam {load_QN}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
$tempAcq addHarness $tempHarness
release_obj $tempHarness

$tempAcq setHarnessName default
$tempTest addAcquisition $tempAcq
release_obj $tempAcq

$tempTestColl addTest $tempTest
release_obj $tempTest

set tempTestColl

